### ISSUE TITLE
The re-sizing gets confused if the jmol display is hidden on page-load

### ISSUE THREAD

**Issue by timhunt** [geoffrowland/moodle-filter_jmol#19]
Sorry, I don't have a fix for this, at least, not yet. But, having found it, I thought I should report it.

Suppose that when the page loads, the JMol display is initially hidden. Then, when you expand that region of the page, the JMol display is tiny (2px by 2px).

We are seeing this with a custom OU course-format. However, expect you can reproduce the problem with https://moodle.org/plugins/format_topcoll.

I suspect this is a bug with YUI resize widget. The code in filter.php seems to me to be doing the right thing setting sensible min and max sizes. It is just a pity that does not work.

**Comment by geoffrowland** [comment]
Thanks Tim. Have never seen this as have not tested with Collapsed Topics course format.
One suggestion. With the 'demise' of YUI, had been considering replacing the YUI Resize code with jQueryUI Resizable. 
http://jqueryui.com/resizable/
No idea if it will help, but you never know...
BTW Does the full-screen option work with your OU course format?

**Comment by timhunt** [comment]
Yes. It works fine if you can spot the tiny 2px by 2px thing, and manually resize it bigger.

**Comment by geoffrowland** [comment]
Can confirm I see same issue with Collapsed Topics format. Also, commenting out the YUI resize code from filter.php avoids the problem, showing it is, indeed, related to the YUI resize widget. 

You are probably aware that without the YUI resize you can still set a fixed-size Jmol/Jsmol object by adding a parameter to the URL e.g ?c=400 will set a 400px x 400px object. 

That said, I find the resizability useful. Display of Jmol/JSmol is often a compromise between size and performance, since the rendering process is roughly dependent on the square of the dimensions. This is particularly so for the JavaScript version (JSmol) which is significantly slower than the Java version (Jmol). So, it is useful to have this under the control of the end-user. I find it most useful to have a course layout with just one column of blocks, on the left-hand side, to accommodate the resizing.

Now I can test the issue, will investigate use of jQuery UI Resizable as an alternative.

**Comment by timhunt** [comment]
I agree the resize functionality is good and should be kept. Would be good if you can find a fix. Thanks.

**Comment by geoffrowland** [comment]
Partial solution using CSS resize, instead of YUI resize, now available as cssresize branch.

Only partial, as CSS resize currently only works with Firefox, Safari, Chrome and Opera. Not yet supported by Internet Explorer or Edge. That said, this is similar behaviour to current textarea resizing in Moodle.

http://caniuse.com/#feat=css-resize

If this does not meet your needs, then there may still be some mileage with jQuery UI resizable. This works well in my hands in a simple web page (not Moodle) for a resizable iframe containing JSmol.
Now need to do some more work untangling PHP from JavaScript! and getting my head around the latest Moodle JavaScript guidelines.

**Comment by timhunt** [comment]
Thanks for looking into this.

I did not know about CSS resize. Worth knowing about, even if IE does not support it yet.

There is this 'polyfill' that claims to make it work in IE https://github.com/CezaryDanielNowak/css-resize-polyfill. I wonder how easy it would be to integrate that?

**Comment by geoffrowland** [comment]
No, I didn't know about CSS resize either, until I started looking into this. Had already tried the polyfill, but   initially discounted it as it did not work, in my hands, directly with iframes. Just took another look and it does seem to work resizing a div, containing an iframe (displaying JSmol) with height and width set to 100%. So, thanks for the reminder. The polyfill should be simpler to implement and more lightweight than YUI resize or jQuery UI resizable. Now to see if it works with Moodle and Collapsed Topics...

**Comment by geoffrowland** [comment]
In my hands, the css resize polyfill works well in simple cases e.g. resizing textarea ordiv with all browsers tested. However, behaves erratically when resizing, specifically shrinking, an iframe (sized at 100%) inside a resizable div. So, not yet an option.

**Comment by geoffrowland** [comment]
Hi Tim. 

Now have a more-or-less drop-in replacement, for YUI3 Resize, using jQueryUI Resizable which behaves itself with the Collapsed Topics course-format and works with all the recent browsers I have tested. So, see if the jqueryuiresizable branch on GitHub works with your custom OU course-format.

Currently uses a pretty basic (using script and link tags) integration of jQuery (already bundled as part of jmol) jQueryUI (now added to the the Jmol filter bundle) and jqueryui.css (also added to the the Jmol filter bundle) - but it works!

I had no luck with the Jmol filter using any of the following, though may be doing something stupid.
$PAGE->requires->jquery();
$PAGE->requires->jquery_plugin('ui');
$PAGE->requires->jquery_plugin('ui-css');

Also, not yet got my head around the new AMD modular way of doing things.

Will investigate refining/modularising things further and moving the relevant jqueryui.css to filter.css if the jQueryUI Resizable fix works in your hands. 

In the longer term, CSS Resize may be the best option but, until all browsers consistently support CSS resize, jQueryUI Resizable seems to be the best short-term solution (assuming no other jQuery/jQueryUI conflicts).

**Comment by markchaneyuk** [comment]
Hi Geoff, 
Do you have an update on this issue? We are having the same issue with Collapsed Topics and Grid Format. I was just wondering if your fix has made its way into master at all, and onto Moodle.org? 
Mark

**Comment by geoffrowland** [comment]
Hi Mark,

The jQueryUI Resizable fix is in the jqueryuiresizable branch: https://github.com/geoffrowland/moodle-filter_jmol/tree/jqueryuiresizable. This works for me with Collapsed Topics. Not tried Grid Format. Was waiting for some user feedback/confirmation of the fix before merging with master or moving onto the Moodle.org plugins repo. Does it work for you?

There is also a partial (does not work with IE/Edge) fix using CSS. Available from the cssresize branch; https://github.com/geoffrowland/moodle-filter_jmol/tree/cssresize. In the longer term this is likely to be the best option and should avoid other JavaScript clashes. However, is not yet supported across all browsers.

Both of these should be equivalent to the master branch apart from the different resize mechanism.

**Comment by timhunt** [comment]
Apologise. Testing out your fix with the OU's theme keeps not quite getting to the top of my todo list, and work time does not look like getting any less manic for the next couple of weeks. However, I really hope this fix works for us, we need it.

**Comment by ebithell** [comment]
Tested and largely working in both Grid Format and Collapsed Topics now with the jQueryUI Resizable fix - thanks for implementing this. Not so good though if the ?i=0 parameter is used (load structure immediately) - a JSmol-loading spinner appears but the molecules never renders.

**Comment by geoffrowland** [comment]
Good! I had not tested with Grid Format.
Can also confirm the ?i=0 parameter causes the structure not to render. Will investigate further. There have been some recent updates, involving the spinner etc, at the JSmol-end-of-things, so I'll look to bundling the very latest version. 

In the short term can only suggest that avoiding the ?i=0 parameter is the lesser of evils. Only needs one more mouse-click to render the molecule and gives improved page loading with multiple JSmol instances.

**Comment by geoffrowland** [comment]
I have now tweaked the cover image logic to work around the issue when the ?i=0 parameter is used with Collapsed Topics. It does mean that the user has to click on a cover image when a Collapsed Topic is first unhidden, but otherwise the ?i=0 parameter works more-or-less as expected with the cover image being automatically replaced by the interactive Jmol/JSmol instance when it has finished loading. It can be good to use the PNGJ format where the cover image matches the initial interactive display. I'll shortly update the Wiki filter documentation to detail this and other recently added features.

Have now merged this into the master branch (replacing YUI3 Resize with jQuery-UI Resizable) together with an update to the latest stable Jmol/JSmol 14.4.4.

If this is effectively solves this issue, and does not introduce any other nasty bugs, I'll update the Moodle plugins database.

Thanks for the testing/feedback

Geoff

**Comment by ebithell** [comment]
That sounds a good solution. Unfortunately I can't test this at the moment (our test environment is in a code freeze) but I'll continue to watch this issue and will test when I can, unless someone else gets there first.

**Comment by timhunt** [comment]
I am sorry that it has taken me so long to check this out (oh dear! pun wasn't intended).

Anyway, I can how report that this works for us, using latest master as of today (ee48f8d7ca753a19d9f1fb4f9d2a1063bf115bd4). Thank you very much for fixing this.

Marking closed.
